# Generated by Django 2.1.4 on 2019-02-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SnoozioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=3)),
                ('exercise', models.TextField(help_text='How Many Hours a week do you exercise?')),
            ],
        ),
    ]
