# Generated by Django 2.1.4 on 2019-02-09 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SnoozioApp', '0002_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, help_text='What is your name?', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='exercise',
            field=models.CharField(help_text='How Many Hours a week do you exercise?', max_length=3),
        ),
    ]
