# Generated by Django 2.2 on 2019-05-02 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SnoozioApp', '0003_auto_20190209_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.CharField(default=18, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='calories',
            field=models.CharField(default=2000, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='exercise_time',
            field=models.CharField(default=5, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='work_time',
            field=models.CharField(default=5, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='exercise',
            field=models.IntegerField(help_text='How Many Hours a week do you exercise?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(blank=True, help_text='What is your name?', max_length=50),
        ),
    ]
