# Generated by Django 2.2 on 2019-05-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SnoozioApp', '0004_auto_20190502_1252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
