# Generated by Django 2.2 on 2019-05-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SnoozioApp', '0006_auto_20190506_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sleeptime',
        ),
    ]
