# Generated by Django 2.2 on 2019-05-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SnoozioApp', '0007_remove_profile_sleeptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(max_length=20),
        ),
    ]
