# Generated by Django 2.2 on 2019-05-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SnoozioApp', '0009_auto_20190506_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(max_length=20),
        ),
    ]
