# Generated by Django 2.2 on 2019-05-07 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SnoozioApp', '0011_sleeptimes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleeptimes',
            name='sleep_time',
        ),
    ]
