# Generated by Django 2.2 on 2019-05-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SnoozioApp', '0012_remove_sleeptimes_sleep_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleeptimes',
            name='end_time',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
