# Generated by Django 2.2 on 2019-05-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SnoozioApp', '0014_auto_20190508_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleeptimes',
            name='total_sleep',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
